[platformio]
default_envs = wb3s

[env]
platform = libretiny
framework = arduino
monitor_speed = 115200
lib_deps =
  file://deps/supla-device
  paulstoffregen/OneWire
  milesburton/DallasTemperature
  adafruit/DHT sensor library
  ; Optional I2C sensor libs after Wire.h support is available on this target:
  ; adafruit/Adafruit Unified Sensor
  ; adafruit/Adafruit BusIO
  ; adafruit/Adafruit BME280 Library
  ; adafruit/Adafruit BMP280 Library
  ; adafruit/Adafruit Si7021 Library
build_flags =
  -D SUPLA_LIBRETINY
  -D SUPLA_DEVICE_NAME=\"Supla-Tuya\"
  -includeinclude/libretiny_compat.h
  -I include
lib_ldf_mode = deep+

[env:cb3s]
board = cb3s

[env:wb3s]
board = wb3s

[env:cb3s_gui_generic]
board = cb3s
build_flags =
  ${env.build_flags}
  -D SUPLA_USE_GENERATED_PROFILE
extra_scripts = pre:tools/pio_generate_profile.py

[env:wb3s_gui_generic]
board = wb3s
build_flags =
  ${env.build_flags}
  -D SUPLA_USE_GENERATED_PROFILE
extra_scripts = pre:tools/pio_generate_profile.py
